// src/domain/activity/ActivityType.ts
export enum ActivityType {
  REPORT_CREATED = "REPORT_CREATED",
  REPORT_FOLLOWED = "REPORT_FOLLOWED",
  REPORT_UNFOLLOWED = "REPORT_UNFOLLOWED",
  STATUS_CHANGED = "STATUS_CHANGED",
  CLOSE_CONFIRMED = "CLOSE_CONFIRMED",
  REPORT_IN_PROGRESS = "REPORT_IN_PROGRESS",
  REPORT_CLOSED = "REPORT_CLOSED",
  REPORT_CONFIRMED_CLOSE = "REPORT_CONFIRMED_CLOSE",
}
